id = "solarized"
name = "Solarized"
version = "0.0.1"
schema_version = 1
authors = ["harmtemolder"]
description = "Precision colors for machines and people"
repository = "https://github.com/harmtemolder/Solarized.zed"
